#!/bin/zsh
# ==========================================
# ZSH-SPECIFIC CONFIGURATION
# ==========================================

# Advanced Zsh Tab Completion Menu Configuration
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
bindkey '^[[Z' reverse-menu-complete # Shift+Tab to cycle backward
