#!/bin/zsh
# ==========================================
# ZSH-SPECIFIC CONFIGURATION
# ==========================================
fpath=(~/.config/zsh-completions/src $fpath)
#autoload -U colors && colors
# Advanced Zsh Tab Completion Menu Configuration
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
bindkey '^[[Z' reverse-menu-complete # Shift+Tab to cycle backward
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


#fzf-tab Configuration
source ~/.config/fzf-tab/fzf-tab.plugin.zsh
# 1. make Tab act as the continuous trigger (descend into a directory) 
# instead of the default '/'
zstyle ':fzf-tab:*' continuous-trigger 'tab'

# 2. set up standard ctrl-vim keys for scrolling and backing out
#zstyle ':fzf-tab:*' fzf-bindings \
#  'ctrl-j:down' \
#  'ctrl-k:up' \
#  'ctrl-h:backward-delete-char/eof'
#zstyle ':fzf-tab:*' fzf-bindings \
#  'ctrl-j:down' \
#  'ctrl-k:up'
#
source ~/.config/zsh-autosuggestions/zsh-autosuggestions.zsh
